<a href="https://colab.research.google.com/github/MMoltira/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##numpy array

In [7]:
np1=np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
np1=np.array([[1,2],[3,5],[2,0],[4,5]])
np1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [10]:
np1.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [11]:
np1[0,:]

array([1, 2])

## HW6 สร้าง Distance metrix (Euclidean) ของ np2
โดยสร้าง Fucntion สำหรับคำนวน Euclidean Distance

In [ ]:
def Euclidean(data1,data2):
  #process
  return dist

In [16]:
import math

In [17]:
def Manhattan(data1,data2):
    distX = abs(data1[0]-data2[0])
    distY = abs(data1[1]-data2[1])
    return distX+distY

In [18]:
Manhattan(np1[0,:],np1[1,:])

5

In [21]:
dist_mat=np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
5*np.ones((4,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [22]:
for i in range(4):
    for j in range(4):
        dist_mat[i,j]=Manhattan(np1[i,:],np1[j,:])

dist_mat

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])