<a href="https://colab.research.google.com/github/MMoltira/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##numpy array

In [7]:
np1=np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
np1=np.array([[1,2],[3,5],[2,0],[4,5]])
np1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [10]:
np1.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [11]:
np1[0,:]

array([1, 2])