<a href="https://colab.research.google.com/github/MMoltira/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

##numpy array

In [5]:
np1=np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [6]:
np1=np.array([[1,2],[3,5],[2,0],[4,5]])
np1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [7]:
np1.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [8]:
np1[0,:]

array([1, 2])

## HW6 สร้าง Distance metrix (Euclidean) ของ np2
โดยสร้าง Fucntion สำหรับคำนวน Euclidean Distance

In [35]:
def Euclidean(data1,data2):
  #process
  return dist

In [36]:
import math

In [37]:
def Manhattan(data1,data2):
    distX = abs(data1[0]-data2[0])
    distY = abs(data1[1]-data2[1])
    return distX+distY

In [38]:
Manhattan(np1[0,:],np1[1,:])

5

In [39]:
dist_mat=np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
5*np.ones((4,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [41]:
for i in range(4):
    for j in range(4):
        dist_mat[i,j]=Manhattan(np1[i,:],np1[j,:])

dist_mat

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [42]:
def Euclidean(data1,data2):
    distX = pow(abs(data1[0]-data2[0]),2)
    distY = pow(abs(data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [43]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np1[i,:],np1[j,:])
dist_math1


array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

## 26/08/2020
## Distance of nominal or categorical features

### (extra) Pythan data struture (Dictionary)

In [61]:
d_A={'a':1,2:3,3:5,'cat':6}

In [62]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [63]:
d_A['cat']

6

In [64]:
d_A['dog']=[1,2,3,4,5]

In [65]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [66]:
import pandas as pd

In [67]:
data_dict={'color':['red','red','green'],
           'status':['single','married','single']}
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [68]:
data_pd=pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  married
2  green   single

##Categorical feture distance methid#1

In [69]:
list(data_pd.iloc[0,:])

['red', 'single']

In [70]:
def meth1_dist(data1,data2):
    N=0
    print(f'data1 is {data1} and data2 is {data2}')
    for i in range(len(data1)):
        print(f'feture{i} of data is{data1[i]}, feture{i} of data2 is {data2[i]}')
        if data1[i] !=data2[i]:
            N=N+1
            print(f'{data1[i]}is not equal {data2[i]}:updated({N})')
        else:
            print(f'{data1[i]}is equal {data2[i]}')
    return N/len(data1)

In [71]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

data1 is ['red', 'single'] and data2 is ['red', 'married']
feture0 of data isred, feture0 of data2 is red
redis equal red
feture1 of data issingle, feture1 of data2 is married
singleis not equal married:updated(1)


0.5

##Categorical feture distance methid#2

## HW7 calculate distance matrix of data_pd using meth1_dist()

In [72]:
pd.get_dummies(data_pd)

color_green  color_red  status_married  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

การคำนวณแบบ binary 

เป็นเช็คว่าถ้าค่าเท่ากันจะนำไปบวกให้ q แต่ถ้าค่าไม่เท่ากันจะบวกให้ t อิงจากสูตร

In [73]:
data_pd_binary = pd.get_dummies(data_pd)
data_pd_binary

color_green  color_red  status_married  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

In [74]:
def binary_sym_dist(data1,data2) :
      q = 0
      rs = 0
      t = 0
      for i in range(len(data1)) :
           if data1[i] == data2[i] :
              if data1[i] == 1 :
                    q = q+1
              else :
                    t = t+1
           if data1[i] != data2[i] :
                rs = rs+1
      return (rs)/(q+rs+t)

In [75]:
binary_sym_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

0.5

## HW8 calculate distance matrix of data_pd_binary using binary_sym_dist()

In [76]:
binary_sym_dist1 = np.zeros((3,3))
binary_sym_dist1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
for i in range(3):
    for j in range(3):
        binary_sym_dist1[i,j] = binary_sym_dist(list(data_pd_binary.iloc[i,:]),list(data_pd_binary.iloc[j,:]))
binary_sym_dist1

array([[0. , 0.5, 0.5],
       [0.5, 0. , 1. ],
       [0.5, 1. , 0. ]])