<a href="https://colab.research.google.com/github/MMoltira/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
# เกี่ยวกับตัวเลข โดยเป็นตัวเลข หรือตารางตัวเลขอย่างเดียว

##numpy array

In [ ]:
np1=np.array([[1,3,5],[2,4,6]]) # สร้าง numpy array แถวที่ 1-2 
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
np1=np.array([[1,2],[3,5],[2,0],[4,5]]) # สร้าง numpy array แถวที่ 1-4 
np1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [ ]:
np1.T # Transpost สลับแถวเป็นหลัก สลับหลักเป็นแถวใช้คำสั่ง .T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [ ]:
np1[0,:] # ดูข้อมูล แถวแรก(0) ข้อมูลทุกตัว(:)ในแถวแรก

array([1, 2])

## HW 6 สร้าง Distance matrix (Euclidean) ของ np2 โดย สร้าง Function สำหรับคำนวณ Euclidean Distance
โดยสร้าง Fucntion สำหรับคำนวน Euclidean Distance

#คำสั่ง def และหลังจากนั้น function_name เป็นชื่อของฟังก์ชัน และในวงเล็บ () เป็นการกำหนดพารามิเตอร์ของฟังก์ชัน พารามิเตอร์ของฟังก์ชันนั้นสามารถมีจำนวนเท่าไหร่ก็ได้หรือไม่มีก็ได้

In [ ]:
def Euclidean(data1,data2):
  #process
  return dist

In [ ]:
import math

In [ ]:
def Manhattan(data1,data2):
    distX = abs(data1[0]-data2[0]) # ใส่ abs เพื่อให้มันเป็นบวก
    distY = abs(data1[1]-data2[1]) # Y อยู่ตำแหน่งที่ 1
    return distX+distY

In [ ]:
Manhattan(np1[0,:],np1[1,:])

5

.zeros คือ สร้าง array ที่ทุกค่าเป็น 0

In [ ]:
# สร้าง array เปล่า 4x4 มาจากจำนวนข้อมูล .zeros คือ สร้าง array ที่ทุกค่าเป็น 0
dist_mat=np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
5*np.ones((4,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
for i in range(4):
    for j in range(4):
        dist_mat[i,j]=Manhattan(np1[i,:],np1[j,:])

dist_mat

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [ ]:
def Euclidean(data1,data2):
    distX = pow(abs(data1[0]-data2[0]),2)
    distY = pow(abs(data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [ ]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np1[i,:],np1[j,:])
dist_math1


array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

## 26/08/2020
## Distance of nominal or categorical features

### (extra) Pythan data struture (Dictionary)

In [ ]:
d_A={'a':1,2:3,3:5,'cat':6} #เวลาจะเรียกใช้ต้องชี้ค่าทุกครั้ง

In [ ]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [ ]:
d_A['cat'] #เรียก cat จะคืนค่า 6 ที่กำหนดไว้ออกมา

6

เวลาจะเพิ่มค่าใส่ลงไปใน Dictionary โดยที่ index ที่จะเพิ่มค่า dog มี 1 2 3 4 5

In [ ]:
d_A['dog']=[1,2,3,4,5]

In [ ]:
del d_A[2] #คำสั่ง del ใช้ลบค่าใน dict ที่ต้องการออก

In [ ]:
d_A 

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [ ]:
import pandas as pd

In [ ]:
data_dict={'color':['red','red','green'], #ค่า color จะมีทั้งหมด 3 ค่า คือ red green blue
           'status':['single','married','single']} #ค่า status มี 3 ค่า คือ 'single','married','divc'
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

#pd.DataFrame เป็นการสร้างข้อมูลใหม่ใน Dictionary
.from_dict เรียกใช้เพื่อสร้างตาราง

In [ ]:
data_pd=pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  married
2  green   single

##Categorical feture distance methid#1

#Categorical feature distance method#1
คำสั่ง .iloc : มองตารางจาก pandas ให้เป็น Numpy คือ มีแถวและหลัก

In [ ]:
list(data_pd.iloc[0,:]) #ตัวอย่างการเรียกค่าแต่ละ data point โดย 0 คือ ตัวที่ 0 ถ้า 1 ก็คือ red married

['red', 'single']

In [ ]:
def meth1_dist(data1,data2): #data1 data2 คือ ข้อมูลในตารางแต่ละตัว เพื่อมาดูว่า data1 และ data2 ห่างกันเท่าไหร่ โดยที่ความยาวแต่ละค่ามีค่า 2 ตัว
    N=0 #เพื่อให้นับว่ามีทั้งหมดเท่าไหร่
    print(f'data1 is {data1} and data2 is {data2}')
    for i in range(len(data1)):
        print(f'feture{i} of data is{data1[i]}, feture{i} of data2 is {data2[i]}')
        if data1[i] !=data2[i]:
            N=N+1 #จะนับว่ามีฟีเจอร์ที่ไม่เหมือนกันทั้งหมดกี่ตัว
            print(f'{data1[i]}is not equal {data2[i]}:updated({N})')
        else:
            print(f'{data1[i]}is equal {data2[i]}')
    return N/len(data1)

In [ ]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

data1 is ['red', 'single'] and data2 is ['red', 'married']
feture0 of data isred, feture0 of data2 is red
redis equal red
feture1 of data issingle, feture1 of data2 is married
singleis not equal married:updated(1)


0.5

##Categorical feture distance methid#2

## HW7 calculate distance matrix of data_pd using meth1_dist()

In [ ]:
pd.get_dummies(data_pd)

color_green  color_red  status_married  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

การคำนวณแบบ binary 

เป็นเช็คว่าถ้าค่าเท่ากันจะนำไปบวกให้ q แต่ถ้าค่าไม่เท่ากันจะบวกให้ t อิงจากสูตร

In [ ]:
data_pd_binary = pd.get_dummies(data_pd)
data_pd_binary

color_green  color_red  status_married  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

In [ ]:
def binary_sym_dist(data1,data2) :
      q = 0
      rs = 0
      t = 0
      for i in range(len(data1)) :
           if data1[i] == data2[i] :
              if data1[i] == 1 :
                    q = q+1
              else :
                    t = t+1
           if data1[i] != data2[i] :
                rs = rs+1
      return (rs)/(q+rs+t)

In [ ]:
binary_sym_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

0.5

## HW8 calculate distance matrix of data_pd_binary using binary_sym_dist()

In [ ]:
binary_sym_dist1 = np.zeros((3,3))
binary_sym_dist1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
for i in range(3):
    for j in range(3):
        binary_sym_dist1[i,j] = binary_sym_dist(list(data_pd_binary.iloc[i,:]),list(data_pd_binary.iloc[j,:]))
binary_sym_dist1

array([[0. , 0.5, 0.5],
       [0.5, 0. , 1. ],
       [0.5, 1. , 0. ]])